In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]
mylist

[1, 2, 3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nested_list = [[1, 2], [3, 4], [5, 6]]
nested_list

[[1, 2], [3, 4], [5, 6]]

In [5]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [13]:
np.linspace(0, 10, 20, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(2)

array([0.48296262, 0.10190301])

In [16]:
np.random.rand(3, 4)

array([[9.93891241e-01, 4.40640372e-01, 7.35098000e-01, 6.24201173e-01],
       [4.72886333e-01, 4.45183380e-01, 3.63878356e-01, 5.44694705e-04],
       [6.05504214e-02, 1.12575597e-01, 3.93903357e-01, 6.35296656e-01]])

In [17]:
np.random.randn(5,5)

array([[-0.58007228, -0.88229986, -0.03350836,  1.93626218,  1.05039751],
       [ 0.72356807, -0.10457145,  0.8873361 , -1.76337913,  1.10953626],
       [ 0.52661324,  1.4078261 ,  1.07790195, -0.90270599,  0.14813792],
       [-0.53100386, -1.24150416,  0.61883083, -1.08418621, -0.75417327],
       [-0.85934664, -1.87964206,  1.18270511, -1.71510251,  0.70908365]])

In [18]:
np.random.randint(1, 100, 10)

array([34, 16, 39, 84, 61, 75, 21, 62, 88, 10])

In [19]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [20]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [22]:
arr.shape

(25,)

In [23]:
ranarr.shape

(10,)

In [24]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
arr.reshape(5, 2)

ValueError: cannot reshape array of size 25 into shape (5,2)

In [27]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [28]:
ranarr.max()

39

In [29]:
ranarr.argmax()

7

In [30]:
ranarr.min()

2

In [31]:
ranarr.argmin()

9

In [32]:
ranarr.dtype

dtype('int64')

In [33]:
myarr = np.random.rand(4)

In [34]:
myarr

array([0.02058449, 0.96990985, 0.83244264, 0.21233911])

In [35]:
myarr.dtype

dtype('float64')